### ISSUE TITLE
Menu item ordering (see attachment!)

### ISSUE THREAD

**Issue by 1951FDG** [technet/brackets.recentprojects#1]
![nnn](https://cloud.githubusercontent.com/assets/220168/4304448/ec4082d4-3e70-11e4-9595-31d26aeef784.jpg)

**Comment by technet** [comment]
Issue here is, not like other extensions, this one will create menu items dynamically as you close and open projects, so we cannot get hold of menu locations permanently. If we are to do so, then we need to keep pre occupied blank menu locations even though there are no previously opened projects which is not nice. So the problem comes when another extension adds menu items while we're less than five projects so they will get their slot and next time we have to add on top of it. In brackets we don't have ability to define our own menu regions (not the visual separators) 

But next time when you close and open brackets, and it go through each extension in sequence, so it will arrange menu items of one extensions first before the other, and you will get them again in correct position. So this issue is only while you have brackets open and recent projects less than 5 and another extension adding menus to File main menu. 

Will see another alternative to save the grouping mean while

**Comment by 1951FDG** [comment]
Thanks for your thorough explanation. I noticed another issue, seems as if preferences are saved to to both the project '.brackets.json' and the brackets 'brackets.json', it should only be saved to 'brackets.json' !

![mmm](https://cloud.githubusercontent.com/assets/220168/4317698/1564922c-3f16-11e4-851b-66c171927082.jpg)

**Comment by 1951FDG** [comment]
Another thing worth mentioning is that brackets seems to support recentProjects already, but it is not accessible through the menu.

![jjj](https://cloud.githubusercontent.com/assets/220168/4317907/9a337066-3f18-11e4-8907-b21f2c796ab9.jpg)

The location of the file is /Library/Application\ Support/Brackets/state.json (on OS X)
Entry (key) is "recentProjects" and value is an array of strings

Not sure if you knew about this...

**Comment by technet** [comment]
For the first issue (preferences) I used brackets preferences module to load and save project list, so Im not sure why it is writing it to project specific file, to be honest this is my first extension and I didn't even know that there is a preference file for each project and i need to check that. Also Im not writing it directly to the file instead I use brackets module.

For the second thing, yes I've got to know that there is recent project drop down available in brackets, while developing this extension, and I think many users will not notice it, thats what happened to me. Moreover I think Menus should be always at specific places. Built in recent project menu go up and down as you open and close individual files, because it takes the top half of the project tree. So I thought it would be anyway good to have few projects in File menu for easy access.

Thanks a lot for taking time to use and review my extension, my second extension clipbox is written after I gain bit more knowledge in brackets architecture, and tried to tackle most common issue I face when coding that is to copy text from different places without overwriting them and paste whenever needed.
[https://github.com/technet/brackets.clipbox](https://github.com/technet/brackets.clipbox)

**Comment by 1951FDG** [comment]
It's definitely nice to have the projects listed in the file menu, it's actually a standard in OS X cocoa document based apps, Open Recent... 

For the first issue, the project specific file is optional, but very useful. I guess you will need to make sure you always write to the general preferences file.

My suggestion would be to use the built-in `recentProjects`, this saves you from having to write to preferences. But then again, this means the menu items will not always be at specific places like you want them to be.

Also, to my amazement, Brackets doesn't have submenus? With my installed extensions growing, my menus are growing too, it's rather strange there is not support for submenus to organize menu items better.

**Comment by technet** [comment]
Yes thats the problem, if you look at extension git readme I have mentioned the problem with sub menus, if they have supported it, my initial try was to use them, then there won't be any of these issues, probably they may introduce in future, i will take time to fix the issues you mentioned when i get bit of free time, thanks again for pointing them out

Something I noticed that you mentioned you have .brackets.json file in project folder and it also has project list, this is something I don't see in windows platform (I'm using windows) and there is no .brackets.json. flle (I know dot files are common in *nix and mac systems to store individual preferences)  so wonder whether this is something related with OS. anyway I use

``` js
PreferencesManager = brackets.getModule("preferences/PreferencesManager"),
prefs = PreferencesManager.getExtensionPrefs(EXT_NAME);    
```

https://github.com/technet/brackets.recentprojects/blob/master/main.js#L21

to access and store preferences, which is what brackets recommended way, and I don't directly access json files and write, so I guess that may be its default behaviour. 

Anyway I'm still learning brackets architecture, it's hard to find good tutorials covering everything, so had to go through existing extension codes and educated myself :)

**Comment by technet** [comment]
Now using in-built recent project list, and arranging menu  items properly.

**Comment by 1951FDG** [comment]
Thanks for the fixes, works great now, as it fixes other related issues as well.

**Comment by technet** [comment]
Thank you for reviewing it and giving advise :) I mentioned you in release version description.

**Comment by 1951FDG** [comment]
Cool, thanks maybe one day you give me advise, as I am thinking of creating a Brunch extension for Brackets.
